# Generated by Django 4.2.3 on 2023-09-11 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="images",
            new_name="image",
        ),
    ]
